// Code generated by entc, DO NOT EDIT.

package direction

const (
	// Label holds the string label denoting the direction type in the database.
	Label = "direction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDescription holds the string denoting the description vertex property in the database.
	FieldDescription = "description"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"

	// Table holds the table name of the direction in the database.
	Table = "directions"
)

// Columns holds all SQL columns are direction fields.
var Columns = []string{
	FieldID,
	FieldDescription,
	FieldName,
}
