// Code generated by entc, DO NOT EDIT.

package receipt

const (
	// Label holds the string label denoting the receipt type in the database.
	Label = "receipt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldPortions holds the string denoting the portions vertex property in the database.
	FieldPortions = "portions"

	// Table holds the table name of the receipt in the database.
	Table = "receipts"
	// IngredientsTable is the table the holds the ingredients relation/edge.
	IngredientsTable = "ingredients"
	// IngredientsInverseTable is the table name for the Ingredient entity.
	// It exists in this package in order to avoid circular dependency with the "ingredient" package.
	IngredientsInverseTable = "ingredients"
	// IngredientsColumn is the table column denoting the ingredients relation/edge.
	IngredientsColumn = "receipt_ingredient_id"
	// DirectionsTable is the table the holds the directions relation/edge.
	DirectionsTable = "directions"
	// DirectionsInverseTable is the table name for the Direction entity.
	// It exists in this package in order to avoid circular dependency with the "direction" package.
	DirectionsInverseTable = "directions"
	// DirectionsColumn is the table column denoting the directions relation/edge.
	DirectionsColumn = "receipt_direction_id"
)

// Columns holds all SQL columns are receipt fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPortions,
}
