// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// DirectionsColumns holds the columns for the "directions" table.
	DirectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "receipt_direction_id", Type: field.TypeInt, Nullable: true},
	}
	// DirectionsTable holds the schema information for the "directions" table.
	DirectionsTable = &schema.Table{
		Name:       "directions",
		Columns:    DirectionsColumns,
		PrimaryKey: []*schema.Column{DirectionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "directions_receipts_directions",
				Columns: []*schema.Column{DirectionsColumns[3]},

				RefColumns: []*schema.Column{ReceiptsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// IngredientsColumns holds the columns for the "ingredients" table.
	IngredientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "unit_type", Type: field.TypeString},
		{Name: "receipt_ingredient_id", Type: field.TypeInt, Nullable: true},
	}
	// IngredientsTable holds the schema information for the "ingredients" table.
	IngredientsTable = &schema.Table{
		Name:       "ingredients",
		Columns:    IngredientsColumns,
		PrimaryKey: []*schema.Column{IngredientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "ingredients_receipts_ingredients",
				Columns: []*schema.Column{IngredientsColumns[3]},

				RefColumns: []*schema.Column{ReceiptsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ReceiptsColumns holds the columns for the "receipts" table.
	ReceiptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "portions", Type: field.TypeInt},
	}
	// ReceiptsTable holds the schema information for the "receipts" table.
	ReceiptsTable = &schema.Table{
		Name:        "receipts",
		Columns:     ReceiptsColumns,
		PrimaryKey:  []*schema.Column{ReceiptsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DirectionsTable,
		IngredientsTable,
		ReceiptsTable,
		UsersTable,
	}
)

func init() {
	DirectionsTable.ForeignKeys[0].RefTable = ReceiptsTable
	IngredientsTable.ForeignKeys[0].RefTable = ReceiptsTable
}
