// Code generated by entc, DO NOT EDIT.

package ingredient

const (
	// Label holds the string label denoting the ingredient type in the database.
	Label = "ingredient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldUnitType holds the string denoting the unittype vertex property in the database.
	FieldUnitType = "unit_type"

	// Table holds the table name of the ingredient in the database.
	Table = "ingredients"
)

// Columns holds all SQL columns are ingredient fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldUnitType,
}
