// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/matheuslc/dty/ent/direction"
	"github.com/matheuslc/dty/ent/predicate"
)

// DirectionDelete is the builder for deleting a Direction entity.
type DirectionDelete struct {
	config
	predicates []predicate.Direction
}

// Where adds a new predicate to the delete builder.
func (dd *DirectionDelete) Where(ps ...predicate.Direction) *DirectionDelete {
	dd.predicates = append(dd.predicates, ps...)
	return dd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dd *DirectionDelete) Exec(ctx context.Context) (int, error) {
	return dd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (dd *DirectionDelete) ExecX(ctx context.Context) int {
	n, err := dd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dd *DirectionDelete) sqlExec(ctx context.Context) (int, error) {
	var res sql.Result
	selector := sql.Select().From(sql.Table(direction.Table))
	for _, p := range dd.predicates {
		p(selector)
	}
	query, args := sql.Delete(direction.Table).FromSelect(selector).Query()
	if err := dd.driver.Exec(ctx, query, args, &res); err != nil {
		return 0, err
	}
	affected, err := res.RowsAffected()
	if err != nil {
		return 0, err
	}
	return int(affected), nil
}

// DirectionDeleteOne is the builder for deleting a single Direction entity.
type DirectionDeleteOne struct {
	dd *DirectionDelete
}

// Exec executes the deletion query.
func (ddo *DirectionDeleteOne) Exec(ctx context.Context) error {
	n, err := ddo.dd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &ErrNotFound{direction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ddo *DirectionDeleteOne) ExecX(ctx context.Context) {
	ddo.dd.ExecX(ctx)
}
