// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/matheuslc/dty/ent/predicate"
	"github.com/matheuslc/dty/ent/receipt"
)

// ReceiptDelete is the builder for deleting a Receipt entity.
type ReceiptDelete struct {
	config
	predicates []predicate.Receipt
}

// Where adds a new predicate to the delete builder.
func (rd *ReceiptDelete) Where(ps ...predicate.Receipt) *ReceiptDelete {
	rd.predicates = append(rd.predicates, ps...)
	return rd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rd *ReceiptDelete) Exec(ctx context.Context) (int, error) {
	return rd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (rd *ReceiptDelete) ExecX(ctx context.Context) int {
	n, err := rd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rd *ReceiptDelete) sqlExec(ctx context.Context) (int, error) {
	var res sql.Result
	selector := sql.Select().From(sql.Table(receipt.Table))
	for _, p := range rd.predicates {
		p(selector)
	}
	query, args := sql.Delete(receipt.Table).FromSelect(selector).Query()
	if err := rd.driver.Exec(ctx, query, args, &res); err != nil {
		return 0, err
	}
	affected, err := res.RowsAffected()
	if err != nil {
		return 0, err
	}
	return int(affected), nil
}

// ReceiptDeleteOne is the builder for deleting a single Receipt entity.
type ReceiptDeleteOne struct {
	rd *ReceiptDelete
}

// Exec executes the deletion query.
func (rdo *ReceiptDeleteOne) Exec(ctx context.Context) error {
	n, err := rdo.rd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &ErrNotFound{receipt.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rdo *ReceiptDeleteOne) ExecX(ctx context.Context) {
	rdo.rd.ExecX(ctx)
}
