// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Direction is the predicate function for direction builders.
type Direction func(*sql.Selector)

// Ingredient is the predicate function for ingredient builders.
type Ingredient func(*sql.Selector)

// Receipt is the predicate function for receipt builders.
type Receipt func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
